
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Luis Guillermo Abarca
 * 
 */
public class ventanaPaint extends javax.swing.JFrame {
    private static int MAXBORDE = 15;
    
    //Declaramos las variables de los objetos que vamos a pintar
    Line2D.Double linea = new Line2D.Double(); //Variable Linea
    Ellipse2D.Double circulo = new Ellipse2D.Double();//Varialble Circulo
    Rectangle2D.Double cuadrado = new Rectangle2D.Double();//Variable Cuadradp
    //Declaramos los booleanos, que nos servirán para controlar el programa
    //circle, square y line, controlan que dibujar. Discontinua y relleno activaran o desactivaran la linea discontinua y el relleno 
    boolean circle = false, square = false, line = true, discontinua = false, relleno = false;
    //Declaramos un entero para que controle el borde y lo inicializamos a 1
    int borde = 1;
    //Declaramos una variable tipo Color, y la inicializamos a negro
    Color colorSeleccionado = Color.black; 
    
    //Declaramos una variable para almacenar Imagenes, que nos servirá como auxiliar
    private BufferedImage buffer = null;  
 
      
    public ventanaPaint() {
        initComponents();
        //Le damos un tamaño a jDialog1 para tenerlo controlado cuando salga
        jDialog1.setSize(800, 600);
        //Declaramos dos enteros anchoPanel y altoPanel, en los que guardaremos las medidas de jPanel1 
        int anchoPanel = jPanel1.getWidth();
        int altoPanel = jPanel1.getHeight();        
        //Haremos que el buffer "actue como jPanel1", le daremos las mismas medidas que este
        buffer = (BufferedImage) jPanel1.createImage(anchoPanel,altoPanel);
       //A continuacion terminamos de inicializar el buffer
        Graphics2D g2 = buffer.createGraphics();
        g2.setColor(Color.white);
        g2.fillRect(0, 0, anchoPanel, altoPanel);
    }
    //Necesitamos cambiar la funcion paint que viene por defecto
    @Override
    public void paint (Graphics g){
        //Para que los objetos se pinten correctamente tendremos que llamar a paintComponents
        super.paintComponents(g);       
        //Le daremos a g2 el control de jPanel1
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        //Dibujaremos el buffer en  jPanel1
        g2.drawImage (buffer, 0, 0, null);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Borde1 = new javax.swing.JButton();

        jButton4.setText("Aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton4)
                        .addGap(128, 128, 128)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(44, 44, 44))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jButton1.setText("Circulo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("Cuadrado");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Color");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Linea");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });

        jButton7.setText("Discont.");
        jButton7.setToolTipText("");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        jButton8.setText("Relleno");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });

        Borde1.setText("Borde:1");
        Borde1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Borde1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Borde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Borde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //Empezamos inicializando el objeto que toque
        if(line){   //Inicializa la linea
        linea.x1 = evt.getX();
        linea.x2 = evt.getX();
        linea.y1 = evt.getY();
        linea.y2 = evt.getY();
        //Dibuja la linea en el panel
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        g2.draw(linea);
        }
        else if(circle){ //Injcializamos el Circulo
        circulo.x = evt.getX();
        circulo.y = evt.getY();
        circulo.width = circulo.x - evt.getX();
        circulo.height = circulo.y- evt.getY();
        //Dibujamos el circulo en el panel
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        g2.draw(circulo);
        }else if(square)//Inicializamos el Cuadrado
        {
        cuadrado.x = evt.getX();
        cuadrado.y = evt.getY();
        cuadrado.width = cuadrado.x - evt.getX();
        cuadrado.height = cuadrado.y- evt.getY();
        //Dibujamos el cuadrado en el panel
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        g2.draw(cuadrado);
        }

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        //Le damos a g2 el control de jPanel1
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        //Actualizamos jPanel con el contenido del buffer
        g2.drawImage(buffer, 0, 0, null);
        g2.setColor(colorSeleccionado);
        //Comprobamos que estamos dibujando con los booleanos
        if(line){
            linea.x2 = evt.getX();
            linea.y2 = evt.getY();
            g2.draw(linea);
        }else if(circle){
            circulo.width = evt.getX() - circulo.x; // tendremos que restarle x e y respectivamente para que el circulo sea preciso
            circulo.height = evt.getY() - circulo.y;
            g2.draw(circulo);
        }else if(square){
            cuadrado.height = evt.getY() - cuadrado.y; // tendremos que restarle x e y respectivamente para que el cuadrado sea preciso
            cuadrado.width = evt.getX() - cuadrado.x;  //Esto es asi, porque tenemos que partir como punto 0,0 el boton donde se incio el evento
            g2.draw(cuadrado);
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        //Ahora g2 cogerá el control del buffer
        Graphics2D g2 = (Graphics2D) buffer.getGraphics();
        //Configuramos el tamaño del borde mediante una variable entera "borde"
        g2.setStroke(new BasicStroke(borde));
        //Comprobamos si tiene que dibujar la linea discontinua
        if(discontinua){
           float dash[] = {10.0f};
           g2.setStroke(new BasicStroke(borde, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER, 10.0f,dash, 0.0f));
        }
            g2.setColor(colorSeleccionado);//cambiamos el color del objeto a pintar
        if(line){
            g2.draw(linea);    
        }
        else if(circle){
            g2.draw(circulo);  
            if(relleno) //si relleno esta activado rellena el circulo
                g2.fill(circulo);
        }
        else if(square){
            g2.draw(cuadrado);
            if(relleno)//si relleno esta activado rellena el cuadrado
                g2.fill(cuadrado);
        }
        //Ahora apuntaremos a jPanel para actualizar con lo que acabamos de dibujar sobre el buffer
        g2 = (Graphics2D) jPanel1.getGraphics();
        g2.drawImage(buffer, 0, 0, null);
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        jDialog1.setVisible(true);//Al presionar Color, se abrirá la ventana emergente del selector de color, esto lo hara visible
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        //jColorChooser1, coge el color que ha seleccionado el usuario, esto lo guardamos en colorSeleccionado.
        colorSeleccionado = jColorChooser1.getColor();
        jDialog1.setVisible(false);  //"Cerramos" la ventana emergente
        if(colorSeleccionado != jButton3.getForeground()) // si el colorseleccionado no es el mismo que el color de las letras, el color del fondo será cambiado
            jButton3.setBackground(colorSeleccionado);
        else
            jButton3.setBackground(null);
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        jDialog1.setVisible(false);//Al darle a Cancelar cerramos la ventana emergente
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
      //Activa la opcion cuadrado
        circle = false;
        square = true;
        line = false;
        cambiarColorLabel(2);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
         //Activa la opcion linea
        circle = false;
        square = false;
        line = true;
        cambiarColorLabel(0);
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        String continuidad ="";
        if(discontinua == true){
            discontinua = false;
            continuidad = "Discont.";
        }
        else {
            discontinua = true;
            continuidad ="Continua";
        }
        jButton7.setLabel(continuidad);
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        if(relleno == true){
            relleno = false;
            jButton8.setBackground(null);
        }else {
            relleno = true;
            jButton8.setBackground(Color.CYAN);
        }
    }//GEN-LAST:event_jButton8MousePressed

    private void Borde1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borde1MousePressed
       //Cada vez que el usuario pulse este boton el borde aumentara en 1 hasta alcanzar un máximo de MAXBORDE
        String nombreBorde ="";
        borde++;
        if(borde > MAXBORDE)
            borde=1;
        nombreBorde = "Borde:"+borde;
        Borde1.setLabel(nombreBorde);
        
        if(borde == MAXBORDE)
            Borde1.setForeground(Color.RED);
        else
            Borde1.setForeground(null);
    }//GEN-LAST:event_Borde1MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
         //Activa la opcion circulo
        circle = true;
        square = false;
        line = false;
        cambiarColorLabel(1);
    }//GEN-LAST:event_jButton1MousePressed
    private void cambiarColorLabel(int elegido)//Cambia el color de la letra de los botones segun lo que se este dibujando
    {
        switch(elegido)
        {
            case 0:
                jButton6.setForeground(Color.BLUE);
                jButton1.setForeground(null);
                jButton2.setForeground(null);                
                break;
            case 1:
                jButton6.setForeground(null);
                jButton1.setForeground(Color.BLUE);
                jButton2.setForeground(null);
                break;
            case 2:
                jButton6.setForeground(null);
                jButton1.setForeground(null);
                jButton2.setForeground(Color.BLUE);
                break;
        
        
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borde1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
